### ISSUE TITLE
addition

### ISSUE THREAD

**Issue by gustavR0** [gustavR0/project-demo#1]
:sparkles: **additon Feature** :sparkles:
Esta operación debera sumar 2 numeros enteros, reales o string ..
**Unit Tests**:
- [ ] 0 + 2 = 2
- [ ] 0 + 0 = 0
- [ ] -1 + -1 = -2
- [ ] 1 + (-1) = 0 
- [ ]  3.0 + 0.14 = 3.14
- [ ] "Hola" + "Mundo" = "Hola Mundo"

(https://docs.github.com/articles/archiving-cards-on-a-project-board/) or archive all cards in a column

**Comment by gadd-gj** [comment]
nel

**Comment by gustavR0** [comment]
no te pago :-1:

**Comment by gadd-gj** [comment]
Nunca pagas
