### ISSUE TITLE
Division

### ISSUE THREAD

**Issue by gustavR0** [gustavR0/project-demo#6]
:sparkles: **Division** :sparkles:
Esta operación debera dividir 2 numeros enteros, reales
**Unit Tests**:
- [ ] 0 / 2 = 0
- [ ] 0 / 0 = 0
- [ ] -1 / -1 = 1
- [ ] 1 / (-1) = -1 
- [ ]  3.0 / 0.14 = 21.42

**Comment by gadd-gj** [comment]
Te come
